LIBSEL4DEBUG_ALLOC_BUFFER_ENTRIES: "0"
LIBSEL4DEBUG_FUNCTION_INSTRUMENTATION_NONE: true # LibSel4DebugFunctionInstrumentationNone=ON
LIBSEL4DEBUG_FUNCTION_INSTRUMENTATION_TRACE: false
LIBSEL4DEBUG_FUNCTION_INSTRUMENTATION_BACKTRACE: false
LIB_SEL4_DEBUG_FUNCTION_INSTRUMENTAITON: "none"
